name: Deploy Nginx App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: "54.92.199.109"
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "Connecting to EC2..."

            if [ ! -d "nginx-docker-ec2-project" ]; then
              git clone https://github.com/sukhshant-devops/nginx-docker-ec2-project.git
            fi

            cd nginx-docker-ec2-project
            git pull origin main

            echo "Stopping old container..."
            docker rm -f nginx-container || true

            echo "Building image..."
            docker build -t nginx-app .

            echo "Running container..."
            docker run -d --name nginx-container -p 80:80 --restart always nginx-app

            echo "Deployment successful!"
