name: Deploy Nginx App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.92.199.109
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            cd /home/ubuntu

            if [ ! -d "nginx-docker-ec2-project" ]; then
              git clone https://github.com/sukhshant-devops/nginx-docker-ec2-project.git
            fi

            cd nginx-docker-ec2-project
            git pull origin main

            docker rm -f nginx-container || true

            docker build -t nginx-app .

            docker run -d -p 80:80 --name nginx-container --restart always nginx-app
